# Generated by Django 3.0.3 on 2020-02-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Default', max_length=70),
            preserve_default=False,
        ),
    ]
